// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rxD5GLPze2_FpcrgCODcDOW1rIw4viU',
    appId: '1:987810951456:web:c26208f1b805a632b2a745',
    messagingSenderId: '987810951456',
    projectId: 'book-list-sample-eb7ab',
    authDomain: 'book-list-sample-eb7ab.firebaseapp.com',
    storageBucket: 'book-list-sample-eb7ab.appspot.com',
    measurementId: 'G-RR8PK2FQB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsxg_jWroG7rUdezZIBv8wHBhSOSaiCy4',
    appId: '1:987810951456:android:54563a3bdd51b8d4b2a745',
    messagingSenderId: '987810951456',
    projectId: 'book-list-sample-eb7ab',
    storageBucket: 'book-list-sample-eb7ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXlb1QwRcG9PYg-F5YcEE8vuQREI5rAxo',
    appId: '1:987810951456:ios:68c32f7512681b3ab2a745',
    messagingSenderId: '987810951456',
    projectId: 'book-list-sample-eb7ab',
    storageBucket: 'book-list-sample-eb7ab.appspot.com',
    iosBundleId: 'com.example.myFlutterSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXlb1QwRcG9PYg-F5YcEE8vuQREI5rAxo',
    appId: '1:987810951456:ios:68c32f7512681b3ab2a745',
    messagingSenderId: '987810951456',
    projectId: 'book-list-sample-eb7ab',
    storageBucket: 'book-list-sample-eb7ab.appspot.com',
    iosBundleId: 'com.example.myFlutterSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-rxD5GLPze2_FpcrgCODcDOW1rIw4viU',
    appId: '1:987810951456:web:14349dfb4fd462d9b2a745',
    messagingSenderId: '987810951456',
    projectId: 'book-list-sample-eb7ab',
    authDomain: 'book-list-sample-eb7ab.firebaseapp.com',
    storageBucket: 'book-list-sample-eb7ab.appspot.com',
    measurementId: 'G-9HWW4H8CVL',
  );
}
